spring.application.name=livedesk-backend
server.port=3030

#JWT
jwt.secret=${JWT_SECRET:9d4b8c3a7f21e5d60c91a8ef3b74d2a56fe80c19a4d73eb8f2159c4e87d1ab63f9e62d0c18a7b45ef2d9618cb3475fa1e4d83a90bc76f125ed49a8c61f2b73de}
jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}

#Admin
admin.email=${ADMIN_EMAIL:admin@livedesk.com}
admin.password=${ADMIN_PASSWORD:admin123}

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/livedesk
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#Flyway
spring.flyway.enabled=true